-- Deal with typos
vim.cmd("cabbrev WQ wq")
vim.cmd("cabbrev Wq wq")
vim.cmd("cabbrev wQ wq")
vim.cmd("cabbrev Q! q!")
vim.cmd("cabbrev W w")
vim.cmd("cabbrev E e")
vim.cmd("cabbr Qa qa")
vim.cmd("cabbr qA qa")
vim.cmd("cabbr QA qa")
vim.cmd("cabbr Cs cs")
